### ISSUE TITLE
pillow possible udpate

### ISSUE THREAD

**Issue by fmigneault** [plstcharles/thelper#18]
https://github.com/plstcharles/thelper/blob/ee854c3602b2bd5165faaab750c9188e947cfd50/requirements.txt#L7-L8

The constant has been re-added because it broke too many code base. We could consider re-applying `pillow>=7.1` to get latest updates. 
https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#pillow-version-constant

There are a few other changes to consider that could maybe affect some pre-processing: 
https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#default-resampling-filter

I don't think other listed changes will impact us. 

@plstcharles your call

**Comment by plstcharles** [comment]
jeesh, pillow was already not my favorite, this brings my love to a whole new (low) level...

I would rather have pillow>=7.1 than carry around a cursed version forever --- i'll let you push the change in if you want, otherwise i'll put it in the next wave of stuff

**Comment by fmigneault** [comment]
If you can slide it in #15, that should be good.

**Comment by plstcharles** [comment]
done, will be merged into #15
